# Description: Database with minimal MusicBrainz container for replication - ARM64

volumes:
  pgdata:
    driver: local
  dbdump:
    driver: local

services:
  db:
    image: postgres:16-bookworm
    restart: unless-stopped
    command: postgres -c "shared_buffers=1GB" -c "max_connections=100"
    environment:
      - POSTGRES_DB=musicbrainz_db
      - POSTGRES_USER=musicbrainz
      - POSTGRES_PASSWORD=musicbrainz
    shm_size: "1GB"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - dbdump:/media/dbdump
    ports:
      - "5433:5432"
    deploy:
      resources:
        limits:
          memory: 2GB
        reservations:
          memory: 1GB

  musicbrainz:
    build:
      context: ../build/musicbrainz-minimal
    volumes:
      - dbdump:/media/dbdump
      - ./logs:/musicbrainz-server/logs
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=musicbrainz_db
      - POSTGRES_USER=musicbrainz
      - POSTGRES_PASSWORD=musicbrainz
    depends_on:
      - db
      - redis
    deploy:
      resources:
        limits:
          memory: 512MB
        reservations:
          memory: 256MB

  redis:
    image: redis:3-alpine
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256MB
        reservations:
          memory: 128MB
